1:
	clang -Wall -o 1.exe 1.c
	./1.exe

2:
	clang -Wall -o 2.exe 2.c
	./2.exe

3:
	clang -Wall -o 3.exe 3.c
	./3.exe

4:
	clang -Wall -o 4.exe 4.c
	./4.exe

5:
	clang -Wall -o 5.exe 5.c
	./5.exe

permutari:
	clang -Wall -o permutari.exe permutari.c
	./permutari.exe 5
